# Version: 0.0.1

FROM ubuntu
MAINTAINER zhengdalong 'dalong@example.com'
RUN apt-get update && apt-get install -y nginx
RUN echo 'hi, i am in your container' > /usr/share/nginx/html/index.html
EXPOSE 80
